# Compress with ouch
[[mgr.prepend_keymap]]
on = [ "C" ]
run = "plugin ouch"
desc = "Compress with ouch"

# Mount plugin
[[mgr.prepend_keymap]]
on  = "M"
run = "plugin mount"

# SSHFS menu
[[mgr.prepend_keymap]]
on = [ "b" ]
run = "plugin sshfs -- menu"
desc = "Open SSHFS options"

# Lazygit integration
[[mgr.prepend_keymap]]
on = [ "g", "i" ]
run = "plugin lazygit"
desc = "Run lazygit"

# Move in relative steps
[[mgr.prepend_keymap]]
on = [ "n" ]
run = "plugin relative-motions"
desc = "Trigger a new relative motion"
